### ISSUE TITLE
Feature request: Support testing and benchmarking

### ISSUE THREAD

**Issue by cfkaran2** [ronnychevalier/cargo-multivers#4]
This issue is a continuation of #3.  I would like to be able to run all of my tests and benchmarks when using `cargo-multivers`.  I'd also like this to work not just with the built-in tools that cargo has, but also with other tools and libraries such as [`cargo-criterion`](https://crates.io/crates/cargo-criterion), [`cargo-nextest`](https://crates.io/crates/cargo-nextest), etc.

Thank you for making this tool, I fully expect that the performance of my programs will improve significantly, and all without any changes to my code! :smile:

**Comment by Shnatsel** [comment]
There is no need for `cargo multivers` when using it for development. `RUSTFLAGS=-Ctarget-cpu=native cargo test` will be as fast as `cargo multivers` or even slightly faster.

**Comment by cfkaran2** [comment]
@Shnatsel Is there a section in the docs that state that explicitly?  I'm reading https://doc.rust-lang.org/rustc/codegen-options/index.html#target-cpu and https://doc.rust-lang.org/rustc/codegen-options/index.html#target-feature, and while the former does mention the `native` target, I don't see anything that states it will automatically active all of the features of the `native` target.  Is that implied, or am I just misunderstanding what the docs are saying?

Put another way, I'm not sure if the `native` target will activate the features on my CPU, or if it will go for the intersection of the features of all CPUs with similar architectures.

**Comment by Shnatsel** [comment]
`native` not only activates all features of your CPU specifically, but also uses the instruction cost model for your CPU for instruction selection. `cargo multivers` uses a generic cost model instead, resulting in slightly lower performance than `-Ctarget-cpu=native`.

See https://rust-lang.github.io/packed_simd/perf-guide/target-feature/rustflags.html for documentation on this.

**Comment by ronnychevalier** [comment]
@cfkaran2 I just released the version 0.7.0, it contains small fixes so that `cargo multivers` can build tests or benchmarks, not only binaries anymore. However, it does not work directly with other commands like `cargo criterion`, you need to call `cargo multivers -- --bench mybenchmark` for instance to build a benchmark called `mybenchmark`.
I don't think we should improve more than that the support of such use cases.

But as mentioned by @Shnatsel, if you really want to run tests or benchmarks on your machine with optimizations made specifically for you CPU, you should use `RUSTFLAGS=-Ctarget-cpu=native` directly, and do not use `cargo multivers`. The idea behind `cargo multivers` is to build a binary that can be distributed to users with different microarchitecture, but if you only have one microarchitecture to target, there is no need to build your projects for N different microarchitectures.

I hope it answers your question, and if it does feel free to close this issue!

**Comment by ronnychevalier** [comment]
For future reference, I [added a small paragraph](https://github.com/ronnychevalier/cargo-multivers/blob/79035e0eadc2f0cc973803450d36abe252582d41/README.md#intended-use) to remind people that `-Ctarget-cpu=native` can be used instead of `cargo multivers` when they only want to optimize for their CPU.

**Comment by ronnychevalier** [comment]
I'm closing this one since I think everything has been answered, if not please reopen.
